apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ip-root
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"   # HTTP for IP testing
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80