apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-coolcorners
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - coolcorners.org
      secretName: coolcorners-app-tls
  rules:
    - host: coolcorners.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
