apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: ghcr.io/fiservojta/coolcorners-be:0.0.11-6bab750
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db-postgresql-sgp1-67015-do-user-27523279-0.d.db.ondigitalocean.com:25060/defaultdb?sslmode=require&currentSchema=app,public"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { secretKeyRef: { name: db-creds, key: username } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: db-creds, key: password } }
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: "app"
            # Keycloak OAuth2 Configuration
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://coolcorners.org/keycloak/realms/cool-corners"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
