apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: backend-secrets
  namespace: app
spec:
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: cool-corners-b47-r
        envSlug: dev
        secretsPath: /corners/backend
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    - secretName: db-creds
      secretNamespace: app
      creationPolicy: Owner
      template:
        includeAllSecrets: true
