apiVersion: apps/v1
kind: Deployment
metadata:
  name: tato-api
  namespace: tato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tato-api
  template:
    metadata:
      labels:
        app: tato-api
    spec:
      containers:
        - name: tato-api
          image: ghcr.io/fiservojta/tato-be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://CHANGE_ME:5432/tato?sslmode=require
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tato-app-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tato-app-secrets
                  key: db-password
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: https://coolcorners.org/keycloak/realms/tato
            - name: KEYCLOAK_ADMIN_SERVER_URL
              value: https://coolcorners.org/keycloak
            - name: KEYCLOAK_ADMIN_REALM
              value: tato
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: tato-backend
            - name: KEYCLOAK_ADMIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tato-app-secrets
                  key: keycloak-admin-client-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
