apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: keycloak-secrets-sync
  namespace: keycloak
spec:
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: cool-corners-b47-r
        envSlug: dev
        secretsPath: /corners/keycloak
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    - secretName: keycloak-secrets
      secretNamespace: keycloak
      creationPolicy: Owner
      template:
        includeAllSecrets: true
