apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tato-backend-secrets
  namespace: tato
spec:
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: REPLACE_WITH_PROJECT_SLUG
        envSlug: REPLACE_WITH_ENV_SLUG
        secretsPath: /tato-backend
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-system
  managedKubeSecretReferences:
    - secretName: tato-app-secrets
      secretNamespace: tato
      creationPolicy: Owner
      template:
        includeAllSecrets: true
