apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolcorners-keycloak-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FiserVojta/coolcornersdeployment.git # 👈 same repo as backend/frontend apps
    targetRevision: HEAD
    path: keycloak # namespace.yaml + keycloak-infisical-secret.yaml + keycloak-ingress-ip-prefix.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
